require 'mkmf'

# Check if Go is available
go_available = system('go version > /dev/null 2>&1')
unless go_available
  puts "Go is required to build this gem. Please install Go 1.21 or later."
  exit 1
end

# Check if make is available
make_available = system('make --version > /dev/null 2>&1')
unless make_available
  puts "make is required to build this gem. Please install make."
  exit 1
end

# Create a simple Makefile that delegates to the root Makefile
File.open('Makefile', 'w') do |f|
  f.puts <<~MAKEFILE
    # Generated by extconf.rb
    
    all: build
    
    build:
    	cd #{File.expand_path('../..', __dir__)} && make build
    	cp #{File.expand_path('../..', __dir__)}/libmysql_parser.so .
    	cp #{File.expand_path('../..', __dir__)}/libmysql_parser.h .
    
    clean:
    	rm -f libmysql_parser.so libmysql_parser.h
    
    install:
    	mkdir -p $(DESTDIR)$(sitearchdir)
    	cp libmysql_parser.so $(DESTDIR)$(sitearchdir)/
    	cp libmysql_parser.h $(DESTDIR)$(sitearchdir)/
    
    .PHONY: all build clean install
  MAKEFILE
end