name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x86_64
            goos: linux
            goarch: amd64
          - os: ubuntu-latest
            platform: linux
            arch: arm64
            goos: linux
            goarch: arm64
          - os: macos-13
            platform: darwin
            arch: x86_64
            goos: darwin
            goarch: amd64
          - os: macos-latest
            platform: darwin
            arch: arm64
            goos: darwin
            goarch: arm64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - name: Install ARM64 cross-compiler
      if: matrix.goarch == 'arm64' && matrix.goos == 'linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CC: ${{ matrix.goarch == 'arm64' && matrix.goos == 'linux' && 'aarch64-linux-gnu-gcc' || 'gcc' }}
      run: |
        make build
        ls -la libmysql_parser.*

    - name: Run tests
      if: ${{ !(matrix.goarch == 'arm64' && matrix.goos == 'linux') }}
      run: |
        bundle install
        bundle exec rspec

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: libmysql_parser-${{ matrix.platform }}-${{ matrix.arch }}
        path: |
          libmysql_parser.so
          libmysql_parser.h