name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  build-and-release:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: x86_64-linux
            ruby_platform: x86_64-linux
            goos: linux
            goarch: amd64
          - os: ubuntu-latest
            platform: arm64-linux
            ruby_platform: arm64-linux
            goos: linux
            goarch: arm64
          - os: macos-13
            platform: x86_64-darwin
            ruby_platform: x86_64-darwin
            goos: darwin
            goarch: amd64
          - os: macos-latest
            platform: arm64-darwin
            ruby_platform: arm64-darwin
            goos: darwin
            goarch: arm64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - name: Install ARM64 cross-compiler
      if: matrix.goarch == 'arm64' && matrix.goos == 'linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CC: ${{ matrix.goarch == 'arm64' && matrix.goos == 'linux' && 'aarch64-linux-gnu-gcc' || 'gcc' }}
      run: |
        make build
        ls -la libmysql_parser.*

    - name: Build platform-specific gem
      env:
        MYSQL_PARSER_PLATFORM: ${{ matrix.ruby_platform }}
      run: |
        gem build mysql_parser.gemspec
        ls -la *.gem

    - name: Publish platform-specific gem
      env:
        GEM_HOST_API_KEY: "Bearer ${{ secrets.GITHUB_TOKEN }}"
      run: |
        gem push --host https://rubygems.pkg.github.com/${{ github.repository_owner }} *.gem

  release-source-gem:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - name: Build source gem
      run: |
        # Build source gem (no MYSQL_PARSER_PLATFORM env var)
        gem build mysql_parser.gemspec
        ls -la *.gem

    - name: Publish source gem
      env:
        GEM_HOST_API_KEY: "Bearer ${{ secrets.GITHUB_TOKEN }}"
      run: |
        gem push --host https://rubygems.pkg.github.com/${{ github.repository_owner }} *.gem